### ISSUE TITLE
Other Tag Support

### ISSUE THREAD

**Issue by sawyernovak** [uniform-team/Uniform-Validation-Language#33]
Currently, the only tag that works is the valid tag. Support for enabled, visible, and return must be supported as well.

**Comment by dgp1130** [comment]
Added support for all the remaining tags: enabled, visible, selector, and result.

In no particular order:
* selector: A string value which doesn't inherently do anything. It is needed for enabled and visible to be used to their fullest extent.
* enabled: A boolean value which represents whether or not its owner is enabled. Sets the "disabled" property as appropriate on the jQuery element represented by the selector tag. If the selector tag is omitted, then it will infer an input of the owning identifier's name.
* visible: A boolean value which represents whether or not its owner is visible. Calls `jQuery#show()` and `jQuery#hide()` as appropriate on the jQuery element represented by the selector tag. If the selector tag is omitted, then it will infer an input of the owning identifier's name (though doing so looks awful and would probably never be done).
* result: Any type of value which represents the resulting data format of the form. This value is primarily used on the server to be returned to user-code after a form has been successfully validated. This gives them their data in a useful organization immediately while allowing them to take advantage of the same format within the Uniform code.

Car form is essentially complete at this point, it is able to enable/disable or show/hide the form based on the state of the `hasCar` checkbox and works fairly well.

I did come across a minor issue in that the `selector` tag must come before a sibling `enabled` or `visible` tag. I filed #53 to address this when we get to it.

**Comment by dgp1130** [comment]
Regarding your commit comment about overriding an `enabled` or `visible` tag, I had totally forgotten about that. I've updated it so that any `<input />` tag will follow the nearest parent `enabled` tag value. This means that it is possible to do:

```html
<div id="carForm">
    <input name="make" />
    <input name="model" />
</div>
```

```javascript
@carForm {
    selector: "#carForm";
    enabled: hasCar;
    
    make {
        enabled: not hasCar;
    }
}
```

The `model` input will follow `enabled: hasCar`, while the `make` input will follow `enabled: not hasCar` as it is overridden at a nearer DOM node.

Unfortunately, it was not technically feasible to create the same behavior for `visible`. When a node is given the style `display: none`, it collapses with all its children, and I could not find any method of showing a child when its parent is hidden. There are a couple CSS hacks involving the `position` style which we can't really use as we don't want to restyle the form.

Considering it doesn't make a lot of sense anyways, I'm inclined to say that `visible: false` on a parent trumps `visible: true` on a child. I think it is a little more intuitive that way. If people have an issue with that decision, then we can come up with another way of handling it.

**Comment by sawyernovak** [comment]
You mentioned that there was a bug for selector having to be declared before enabled. Is there a ticket for that? Other than that looks good.

**Comment by dgp1130** [comment]
Yes, #53 is the issue to address that problem.
