### ISSUE TITLE
Installation Guide

### ISSUE THREAD

**Issue by sawyernovak** [uniform-team/Uniform-Validation-Language#40]
Code is outdated.

**Comment by dgp1130** [comment]
Few notes here:
* Move `$ npm install` discussion to the top so users know where the `unifom.js` file comes from.
* Added section telling users to copy or symlink the `uniform.js` file to their client code. Gave symlink examples for Unix and Windows. We may want something a little more elegant than this eventually, but we'll have to come back to that later.
* The AJAX functionality you mentioned doesn't exist yet. I'm wondering if we want to mark certain sections as "pending" or "not yet implemented" just so people know that it will _eventually_ work that way, but if you're playing with it now don't expect it to work for you.
* I updated inline code to use backticks `like this` rather than bold **like this**, so we can be consistent  and use GitHub's conventions.
* Removed "Contents" section at the beginning, since installing the client and the server are somewhat intertwined and it doesn't really make since to do one without the other. It would be better for the reader to go through the page top to bottom rather than jumping directly to server installation.
* Updated server code to match new API. We don't use the main selector anymore, since we have a root tag. I also got rid of the template example as I never really liked how that turned out in the original LaTeX doc, I think the formatting on it just made the example more confusing than clarifying.
* Added note on Express `error` callback arguments, since that can be really easy mistake for newcomers to make.

**Comment by sawyernovak** [comment]
I didn't personally go through the steps on a clean machine to see if I could get it working and I don't fully understand a good portion of it, however it seems gramatically fine with me and I will close it for now. We can open it up if (probably inevitably) something changes.
